### ISSUE TITLE
Dark mode is not completely dark

### ISSUE THREAD

**Issue by tageniu** [SerenaKit/Samra#1]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/34309504/222937667-c2d09ed8-9338-4238-8532-6c00b5a454f5.png">

**Comment by SerenaKit** [comment]
OS X version?

**Comment by SerenaKit** [comment]
Should be fixed in https://github.com/SerenaKit/Samra/releases/tag/1.1

**Comment by tageniu** [comment]
> Should be fixed in https://github.com/SerenaKit/Samra/releases/tag/1.1

Thx it's fixed
