### ISSUE TITLE
Add export option (or add image option)

### ISSUE THREAD

**Issue by singlekeycap** [SerenaKit/Samra#4]
Hi! I've noticed apps such as [CarTools](https://github.com/showxu/cartools) have the option to export the icons in the Assets.car file. Would it be possible to implement that in Samra? This would allow me to do things such as add extra icons such as an AppIcon for apps missing one. Otherwise, would it be possible to add an option to add images to the assets? Thanks.

**Comment by SerenaKit** [comment]
> Would it be possible to implement that in Samra?
Sure
> Otherwise, would it be possible to add an option to add images to the assets? Thanks
Complicated and honestly idk how to do that, I'll just add exporting as an option in the "File" menu bar :)

**Comment by singlekeycap** [comment]
Sweet, thanks

**Comment by SerenaKit** [comment]
@singlekeycap Added in 1.2
